### ISSUE TITLE
portal2.php

### ISSUE THREAD

**Issue by mohsenuss91** [mattdean1/gym#1]
I tried to enter in **portal2.php** and I got this

`ERROR: SQLSTATE[28000] [1045] Access denied for user 'test'@'localhost' (using password: YES)
Notice: Undefined variable: row in gym\nocust.php on line 15

Warning: Invalid argument supplied for foreach() in gym\nocust.php on line 16`

**Comment by mattdean1** [comment]
Unfortunately the code won't work without a correct MySQL database set up.
I uploaded it just for my records really.

**Comment by mohsenuss91** [comment]
@mattdean1 please mention it in the readme.md file :)
